version: '3.7'

networks:
  attention-local-network:
    driver: bridge
#postgres
services:
  dbpostgres:
      container_name: mylocal_db_posgres
      image: postgres:13.7
      ports:
        - 5432:5432
      networks:
        - attention-local-network
      volumes:
        - /etc/docker-container/postgres-volume:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=root
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 100M
          reservations:
            cpus: '1'
            memory: 100M



